AWSTemplateFormatVersion: 2010-09-09
Description: Template for basic VPC
Metadata:

Parameters:

Mappings:

Conditions:

Resources:
  Basic_vpc:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: 10.0.0.0/16
    EnableDnsSupport: true
    Tags:
      - Key: environment
        Value: development
Outputs:
